test:
  image: ahughes12/popcorn-base:iptables
  devices:
    - /dev/net/tun
    - /dev/kvm
  environment:
    - NUMx86=1
    - NUMARM=1
    - INTERACTIVE=1
  volumes:
    - /home/popcorn/share:/app/share
    - /home/popcorn/popcorn-kernel:/app/linux
    - /home/popcorn/popcorn-kernel-lib:/app/popcorn-lib
    - /home/popcorn/disks:/app/disks
    - /home/popcorn/gitlab/ccache:/app/ccache
    - /home/popcorn/logs:/app/logs
  privileged: true
