test:
  image: ahughes12/popcorn-base
  devices:
    - /dev/net/tun
    - /dev/kvm
  environment:
    - NUMNODES=2
    - INTERACTIVE=1
  ports:
    # Expose gdb debugger ports
    - 1230:1230
    - 1231:1231
    # Expose SSH over the network
    - 1236:1236
    - 1237:1237
  volumes:
    - /home/popcorn/gitlab/rfc/popcorn-kernel:/app/linux
    - /home/popcorn/gitlab/rfc/popcorn-kernel-lib:/app/popcorn-lib
    - /home/popcorn/disks:/app/disks
    - /home/popcorn/ccache:/app/ccache
    - /home/popcorn/logs:/app/logs
  privileged: true
