test:
  image: ahughes12/popcorn-base
  devices:
    - /dev/net/tun
    - /dev/kvm
  ports:
    # Expose gdb debugger ports
    - 1230:1230
    - 1231:1231
    # Expose SSH over the network
    - 1236:1236
    - 1237:1237
  volumes:
    - /home/popcorn/popcorn-kernel:/app/linux
    - /home/popcorn/popcorn-kernel-lib:/app/popcorn-lib
    - /home/popcorn/disks:/app/disks
    - /home/popcorn/ccache:/app/ccache
    - /home/popcorn/compile.sh:/app/compile.sh
    - /home/popcorn/logs:/app/logs
  privileged: true
